spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            first:
                url: jdbc:mysql://172.16.70.20:3307/renren_fast?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: rd_user
                password: NTHXDF7czYwi
            second:
                url: jdbc:mysql://172.16.70.20:3307/renren_fast?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
                username: rd_user
                password: NTHXDF7czYwi
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
#            总遇到链接超时问题，故将on-borrow打开，如有需要请关闭。
            test-on-borrow: true
            test-on-return: false
#            removeAbandoned: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
